import Head from "next/head";
import Footer from "../Components/Navigation/Footer";
import Navbar from "../Components/Navigation/Navbar";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { Suspense } from "react";

const DynamicContact = dynamic(
  () => import("../Components/ContactUs/ContactUs"),
  {
    suspense: true,
  }
);

export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Suspense>
        <DynamicContact />
      </Suspense>
      <Footer />
    </div>
  );
}
