import Head from "next/head";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { Suspense } from "react";

const DynamicHeader = dynamic(() => import("../Components/Header/Header"), {
  suspense: true,
});
const DynamicStats = dynamic(() => import("../Components/Stats/Stats"), {
  suspense: true,
});
const DynamicCampaigns = dynamic(
  () => import("../Components/Campaign/CampaignsHome/CampaignCards"),
  {
    suspense: true,
  }
);
const DynamicOrgCarousel = dynamic(
  () => import("../Components/OrganizationsCarousel/Carousel"),
  {
    suspense: true,
  }
);

const DynamicCTA = dynamic(() => import("../Components/CTA/CTA"), {
  suspense: true,
});

const DynamicWhyUs = dynamic(() => import("../Components/WhyUs/Home"), {
  suspense: true,
});

export default function Home() {
  return (
    <div className={styles.container} style={{ overflowX: "hidden" }}>
      <Head>
        <title>FundSpirit</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Suspense>
        <DynamicHeader />
        <DynamicStats />
        <DynamicCampaigns />
        <DynamicCTA />
        <DynamicOrgCarousel />
        <DynamicWhyUs />
      </Suspense>
    </div>
  );
}
